// Code generated by "stringer -type Method"; DO NOT EDIT.

package ocitest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownMethod-0]
	_ = x[GetManifest-1]
	_ = x[GetBlob-2]
	_ = x[GetBlobRange-3]
	_ = x[GetTag-4]
	_ = x[ResolveBlob-5]
	_ = x[ResolveManifest-6]
	_ = x[ResolveTag-7]
	_ = x[PushBlob-8]
	_ = x[PushBlobChunked-9]
	_ = x[PushBlobChunkedResume-10]
	_ = x[MountBlob-11]
	_ = x[PushManifest-12]
	_ = x[DeleteBlob-13]
	_ = x[DeleteManifest-14]
	_ = x[DeleteTag-15]
	_ = x[Repositories-16]
	_ = x[Tags-17]
	_ = x[Referrers-18]
}

const _Method_name = "UnknownMethodGetManifestGetBlobGetBlobRangeGetTagResolveBlobResolveManifestResolveTagPushBlobPushBlobChunkedPushBlobChunkedResumeMountBlobPushManifestDeleteBlobDeleteManifestDeleteTagRepositoriesTagsReferrers"

var _Method_index = [...]uint8{0, 13, 24, 31, 43, 49, 60, 75, 85, 93, 108, 129, 138, 150, 160, 174, 183, 195, 199, 208}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
